### ISSUE TITLE
Cannot find the androiddeploy Json file.

### ISSUE THREAD

**Issue by edips** [fjpaz/ComicKron#1]
Hello. I got the error while testing your app:
```
Cannot find the androiddeploy Json file.
Error while building/deploying project ComicKron (kit: Android for armeabi-v7a (GCC 4.9, Qt 5.11.0 for Android armv7))
When executing step "Deploy to Android device"
```
I test your app because I try to understand how to use `ANDROID_DEPLOYMENT_DEPENDENCIES += \` When I use ANDROID_DEPLOYMENT_DEPENDENCIES for a blank code the app is clashes. 
Tested on Qt 5.11 on Manjaro.

**Comment by MyOnlyOnlySunshine** [comment]
Have you solved this problem?

**Comment by edips** [comment]
No I didn't run the app again. But I got it working how to run a minimal qml app with ANDROID_DEPLOYMENT_DEPENDENCIES. I have an example app about it in my repo

**Comment by SEBABIBAN** [comment]
xc

**Comment by SEBABIBAN** [comment]
Have you solved this problem?
